import type { Metadata } from "next";
import { Container } from "@/components/layout/container";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: "Terms for using Mattress Match Score.",
};

export default function TermsPage() {
  return (
    <Container className="max-w-3xl py-10 sm:py-14">
      <h1 className="text-3xl font-bold tracking-tight text-slate-900">Terms of Use</h1>
      <p className="mt-3 text-slate-600">Last updated 2026-09-01.</p>

      <div className="mt-6 space-y-6 text-slate-600">
        <section>
          <h2 className="text-lg font-semibold text-slate-900">Decision support, not a guarantee</h2>
          <p className="mt-2">
            Match Scores are estimates generated by a rule-based scoring engine from the information you provide.
            They are decision-support tools, not a guarantee that any mattress will be comfortable for you. Always
            use a manufacturer's sleep trial to confirm fit.
          </p>
        </section>
        <section>
          <h2 className="text-lg font-semibold text-slate-900">Not medical advice</h2>
          <p className="mt-2">
            Nothing on this site is medical advice. Comfort-focus and BMI-range inputs are used only to refine
            mattress-fit estimates and should not be treated as health guidance.
          </p>
        </section>
        <section>
          <h2 className="text-lg font-semibold text-slate-900">Third-party retailers</h2>
          <p className="mt-2">
            Purchases made through outbound retailer links are between you and that retailer, subject to their own
            terms, pricing, and return policies.
          </p>
        </section>
        <section>
          <h2 className="text-lg font-semibold text-slate-900">Changes</h2>
          <p className="mt-2">
            We may update the scoring model, catalog data, or these terms over time. The current scoring model
            version is always shown alongside every recommendation.
          </p>
        </section>
      </div>
    </Container>
  );
}
